### ISSUE TITLE
Unknown MySQL server host.

### ISSUE THREAD

**Issue by ghost** [RikiBorders/Instagram_CommentBot#1]
When running the installer.py file, I receive the error:

`mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'redacted' (11001)`

I understand the mySQL databases weren't uploaded to the project repo like you mentioned, do we have to create our own mySQL database and configure it in the database_functions.py for it to run?

Could you point out a quick way / video of setting up a mySQL to easily run the bot on?

Thanks.

**Comment by RikiBorders** [comment]
This is unintended. I suspect authentication was disabled on the bot itself, but not the installer hence this error. I wouldn't expect anyone to setup a database to get the bot going. I'll check out the issue today and I'll get back to you when I resolve this issue.

**Comment by RikiBorders** [comment]
Update: 

I disabled the need to authenticate with a database on the launch of the interface. You won't be able to run the installer, but that's no problem as long as the interface boots. I originally created the installer in order to prevent piracy.

I'll update the repository's documentation, but to run the bot all you need to do is clone this repository, and run interface.py.
